---
apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Address
metadata:
  name: example-address
spec:
  forProvider:
    addressType: EXTERNAL
    region: us-east1
  providerConfigRef:
    name: example
---
apiVersion: compute.gcp.crossplane.io/v1alpha1
kind: Firewall
metadata:
  name: example
spec:
  forProvider:
    allowed:
      - IPProtocol: tcp
        ports: ["80", "443"]
      - IPProtocol: icmp
    sourceRanges: ["10.0.0.0/24"]
    networkRef:
      name: example
  providerConfigRef:
    name: example
---
apiVersion: compute.gcp.crossplane.io/v1beta1
kind: GlobalAddress
metadata:
  name: example-global-address
spec:
  forProvider:
    addressType: INTERNAL
    purpose: VPC_PEERING
  providerConfigRef:
    name: example
---
apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Network
metadata:
  name: example
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingConfig:
      routingMode: REGIONAL
  providerConfigRef:
    name: example
---
apiVersion: compute.gcp.crossplane.io/v1alpha1
kind: Router
metadata:
  name: router-test
spec:
  forProvider:
    description: A test router to verify provider-gcp changes
    region: us-west1
    networkRef:
      name: network-example
    nats:
      - name: router-nat-1
        minPortsPerVm: 2
        natIpAllocateOption: AUTO_ONLY
        sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
  providerConfigRef:
    name: default
---
apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Subnetwork
metadata:
  name: example
spec:
  forProvider:
    region: us-central1
    ipCidrRange: "192.168.0.0/24"
    privateIpGoogleAccess: true
    secondaryIpRanges:
      - rangeName: pods
        ipCidrRange: 10.128.0.0/20
      - rangeName: services
        ipCidrRange: 172.16.0.0/16
    networkRef:
      name: example
  providerConfigRef:
    name: example
